/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Clases.*;
import Paneles.*;
import paneles.CambiaPanel;

/**
 *
 * @author fiore
 */
public class MainMenuPro extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuPro
     */
    public MainMenuPro() {
        initComponents();
        this.setLocationRelativeTo(this);
        jTextName.setEditable(false);
        PanelBienvenida pB= new PanelBienvenida(); 
        new CambiaPanel(jPanelPrincipal, pB);
        ponerNombre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rSButtonTutoria = new rsbutton.RSButtonMetro();
        rSButtonNotas = new rsbutton.RSButtonMetro();
        rSButtonAula = new rsbutton.RSButtonMetro();
        rSButtonHorario = new rsbutton.RSButtonMetro();
        rSButtonAgenda = new rsbutton.RSButtonMetro();
        jButton1 = new javax.swing.JButton();
        jPanelSuperior = new javax.swing.JPanel();
        jButtonMenu = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelMenu.setBackground(new java.awt.Color(204, 204, 204));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Insignia_Colegio.png"))); // NOI18N

        jTextName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextName.setBorder(null);
        jTextName.setOpaque(false);
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido(a)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(0, 80, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextName, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanelMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 270));

        rSButtonTutoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/person-3x.png"))); // NOI18N
        rSButtonTutoria.setText("Tutoria");
        rSButtonTutoria.setActionCommand("ALUMNO");
        rSButtonTutoria.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonTutoria.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonTutoria.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonTutoria.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonTutoria.setIconTextGap(16);
        rSButtonTutoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonTutoriaActionPerformed(evt);
            }
        });
        jPanelMenu.add(rSButtonTutoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 40));

        rSButtonNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clipboard-3x.png"))); // NOI18N
        rSButtonNotas.setText("Notas");
        rSButtonNotas.setActionCommand("ALUMNO");
        rSButtonNotas.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonNotas.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonNotas.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonNotas.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonNotas.setIconTextGap(30);
        rSButtonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonNotasActionPerformed(evt);
            }
        });
        jPanelMenu.add(rSButtonNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 40));

        rSButtonAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book-3x.png"))); // NOI18N
        rSButtonAula.setText("Aula");
        rSButtonAula.setActionCommand("ALUMNO");
        rSButtonAula.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonAula.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonAula.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonAula.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonAula.setIconTextGap(40);
        rSButtonAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonAulaActionPerformed(evt);
            }
        });
        jPanelMenu.add(rSButtonAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 40));

        rSButtonHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock-3x.png"))); // NOI18N
        rSButtonHorario.setText("Horario");
        rSButtonHorario.setActionCommand("ALUMNO");
        rSButtonHorario.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonHorario.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonHorario.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonHorario.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonHorario.setIconTextGap(20);
        rSButtonHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHorarioActionPerformed(evt);
            }
        });
        jPanelMenu.add(rSButtonHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 280, 40));

        rSButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar-3x.png"))); // NOI18N
        rSButtonAgenda.setText("Agenda");
        rSButtonAgenda.setActionCommand("ALUMNO");
        rSButtonAgenda.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonAgenda.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonAgenda.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonAgenda.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonAgenda.setIconTextGap(24);
        rSButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonAgendaActionPerformed(evt);
            }
        });
        jPanelMenu.add(rSButtonAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 280, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salir.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, -1, -1));

        jPanelSuperior.setBackground(new java.awt.Color(0, 51, 204));
        jPanelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMenu.setBackground(new java.awt.Color(0, 51, 204));
        jButtonMenu.setForeground(new java.awt.Color(0, 51, 204));
        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        jButtonMenu.setToolTipText("");
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanelSuperior.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setAlignmentX(0.0F);
        jPanelPrincipal.setLayout(new javax.swing.BoxLayout(jPanelPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE))
            .addComponent(jPanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonTutoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonTutoriaActionPerformed
    int n = Colegio.existeBuscarProf(Colegio.idProfeIniciado);
        String tut = Colegio.listaProf[n].tutoria();
        
        if(tut !=null){
            PanelTutoria pT= new PanelTutoria(); 
            new CambiaPanel(jPanelPrincipal, pT);
        }else{
            PanelNoTutor pT= new PanelNoTutor(); 
            new CambiaPanel(jPanelPrincipal, pT);
        }
    }//GEN-LAST:event_rSButtonTutoriaActionPerformed

    private void ponerNombre(){
        int n = Colegio.existeBuscarProf(Colegio.idProfeIniciado);
        if(n>=0){
            String nC =  Colegio.listaProf[n].getNombre() + " " + Colegio.listaProf[n].getApellido();
            jTextName.setText("Profesor(a) " +nC);
        }
    }
    private void rSButtonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonNotasActionPerformed
        PanelNotas pN= new PanelNotas(); 
        new CambiaPanel(jPanelPrincipal, pN);
    }//GEN-LAST:event_rSButtonNotasActionPerformed

    private void rSButtonAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonAulaActionPerformed
        PanelAulaPro pAP= new PanelAulaPro(); 
        new CambiaPanel(jPanelPrincipal, pAP);
    }//GEN-LAST:event_rSButtonAulaActionPerformed

    private void rSButtonHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHorarioActionPerformed
        PanelHorarioProfe pHP= new PanelHorarioProfe(); 
        new CambiaPanel(jPanelPrincipal, pHP);
    }//GEN-LAST:event_rSButtonHorarioActionPerformed

    private void rSButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonAgendaActionPerformed
        PanelAgenda pA= new PanelAgenda(); 
        new CambiaPanel(jPanelPrincipal, pA);
    }//GEN-LAST:event_rSButtonAgendaActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        int posicion = jPanelMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -280, 2, 2, jPanelMenu);
        }else{
            Animacion.Animacion.mover_derecha(-280, 0, 2, 2, jPanelMenu);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InicioSesion is = new InicioSesion();
        is.setResizable(false);
        is.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
       
    }//GEN-LAST:event_jTextNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextName;
    private rsbutton.RSButtonMetro rSButtonAgenda;
    private rsbutton.RSButtonMetro rSButtonAula;
    private rsbutton.RSButtonMetro rSButtonHorario;
    private rsbutton.RSButtonMetro rSButtonNotas;
    private rsbutton.RSButtonMetro rSButtonTutoria;
    // End of variables declaration//GEN-END:variables
}
