/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Clases.*;
import Paneles.*;
import paneles.CambiaPanel;

/**
 *
 * @author fiore
 */
public class MainMenuAdm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuAdm
     */
    public MainMenuAdm() {
        initComponents();
        this.setLocationRelativeTo(this);
        jTextName.setEditable(false);
        //jTextName.setText(Colegio.admin.getCargo() + " " + Colegio.admin.getNombre() + " " + Colegio.admin.getApellido());
        PanelBienvenida pB= new PanelBienvenida(); 
        new CambiaPanel(jPanelPrincipal, pB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelMenu1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rSButtonAlumno = new rsbutton.RSButtonMetro();
        rSButtonProfesor = new rsbutton.RSButtonMetro();
        rSButtonAula = new rsbutton.RSButtonMetro();
        rSButtonAgenda = new rsbutton.RSButtonMetro();
        jButton1 = new javax.swing.JButton();
        jPanelSuperior = new javax.swing.JPanel();
        jButtonMenu = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jPanelMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Insignia_Colegio.png"))); // NOI18N

        jTextName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextName.setBorder(null);
        jTextName.setOpaque(false);
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextName)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelMenu1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 280, 260));

        rSButtonAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/person-3x.png"))); // NOI18N
        rSButtonAlumno.setText("Alumno");
        rSButtonAlumno.setActionCommand("ALUMNO");
        rSButtonAlumno.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonAlumno.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonAlumno.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonAlumno.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonAlumno.setIconTextGap(16);
        rSButtonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonAlumnoActionPerformed(evt);
            }
        });
        jPanelMenu1.add(rSButtonAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 40));

        rSButtonProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/briefcase-3x.png"))); // NOI18N
        rSButtonProfesor.setText("Profesor");
        rSButtonProfesor.setActionCommand("ALUMNO");
        rSButtonProfesor.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonProfesor.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonProfesor.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonProfesor.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonProfesor.setIconTextGap(15);
        rSButtonProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonProfesorActionPerformed(evt);
            }
        });
        jPanelMenu1.add(rSButtonProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 40));

        rSButtonAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book-3x.png"))); // NOI18N
        rSButtonAula.setText("Aula");
        rSButtonAula.setActionCommand("ALUMNO");
        rSButtonAula.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonAula.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonAula.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonAula.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonAula.setIconTextGap(40);
        rSButtonAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonAulaActionPerformed(evt);
            }
        });
        jPanelMenu1.add(rSButtonAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 280, 40));

        rSButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar-3x.png"))); // NOI18N
        rSButtonAgenda.setText("Agenda");
        rSButtonAgenda.setActionCommand("ALUMNO");
        rSButtonAgenda.setColorHover(new java.awt.Color(51, 102, 255));
        rSButtonAgenda.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonAgenda.setColorPressed(new java.awt.Color(0, 0, 204));
        rSButtonAgenda.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonAgenda.setIconTextGap(24);
        rSButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonAgendaActionPerformed(evt);
            }
        });
        jPanelMenu1.add(rSButtonAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 280, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salir.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelMenu1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, -1, -1));

        jPanelSuperior.setBackground(new java.awt.Color(0, 51, 204));
        jPanelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMenu.setBackground(new java.awt.Color(0, 51, 204));
        jButtonMenu.setForeground(new java.awt.Color(0, 51, 204));
        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        jButtonMenu.setToolTipText("");
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanelSuperior.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setAlignmentX(0.0F);
        jPanelPrincipal.setLayout(new javax.swing.BoxLayout(jPanelPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE))
            .addComponent(jPanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonAlumnoActionPerformed
        PanelAlumnoAdm pA= new PanelAlumnoAdm(); 
        new CambiaPanel(jPanelPrincipal, pA);
    }//GEN-LAST:event_rSButtonAlumnoActionPerformed

    private void rSButtonProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonProfesorActionPerformed
        PanelProfesorAdm pP= new PanelProfesorAdm(); 
        new CambiaPanel(jPanelPrincipal, pP);
    }//GEN-LAST:event_rSButtonProfesorActionPerformed

    private void rSButtonAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonAulaActionPerformed
        PanelAulaAdm pA= new PanelAulaAdm(); 
        new CambiaPanel(jPanelPrincipal, pA);
    }//GEN-LAST:event_rSButtonAulaActionPerformed

    private void rSButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonAgendaActionPerformed
        PanelAgenda pA= new PanelAgenda(); 
        new CambiaPanel(jPanelPrincipal, pA);
    }//GEN-LAST:event_rSButtonAgendaActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        int posicion = jPanelMenu1.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -280, 2, 2, jPanelMenu1);
        }else{
            Animacion.Animacion.mover_derecha(-280, 0, 2, 2, jPanelMenu1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InicioSesion is = new InicioSesion();
        is.setResizable(false);
        is.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextName;
    private rsbutton.RSButtonMetro rSButtonAgenda;
    private rsbutton.RSButtonMetro rSButtonAlumno;
    private rsbutton.RSButtonMetro rSButtonAula;
    private rsbutton.RSButtonMetro rSButtonProfesor;
    // End of variables declaration//GEN-END:variables
}
