/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Clases.Colegio;

/**
 *
 * @author jhona
 */
public class MostrarHorarioAula extends javax.swing.JDialog {

    /**
     * Creates new form MostrarHorarioAula
     */
    public MostrarHorarioAula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        mostrarAula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHorarioAula = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Horario del Aula");
        jLabel15.setOpaque(true);

        jTableHorarioAula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableHorarioAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null}
            },
            new String [] {
                "Horario", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHorarioAula.setRowHeight(55);
        jTableHorarioAula.getTableHeader().setResizingAllowed(false);
        jTableHorarioAula.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableHorarioAula);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public void mostrarAula(){
        int pos=Colegio.existeBuscarAula(Colegio.idAulaSelect);
        char nivel=Colegio.listaAula[pos].getCodigo().charAt(0);
        if(nivel=='I'){
            String matris[][]=new String[6][6];
            matris[0][0]="8:00-8:45";
            matris[1][0]="8:45-9:30";
            matris[2][0]="9:30-10:00";
            matris[3][0]="10:00-10:45";
            matris[4][0]="10:45-11:30";
            matris[5][0]="11:30-12:15";
            String hor[][]=Colegio.listaAula[pos].getHa().getHor();
            for(int i=0;i<6;i++){
                for(int j=1;j<6;j++){
                    matris[i][j]=hor[i][j-1];
                }
            }
            jTableHorarioAula.setModel(new javax.swing.table.DefaultTableModel(
                //Aquí pondremos la matriz
                matris,
                new String [] {
                    "Horario", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, true, true, true, true, true
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        }else if(nivel=='P'){
            String matris[][]=new String[7][6];
            matris[0][0]="8:00-8:45";
            matris[1][0]="8:45-9:30";
            matris[2][0]="9:30-10:15";
            matris[3][0]="10:15-10:45";
            matris[4][0]="10:45-11:30";
            matris[5][0]="11:30-12:15";
            matris[6][0]="12:15-13:00";
            String hor[][]=Colegio.listaAula[pos].getHa().getHor();
            for(int i=0;i<7;i++){
                for(int j=1;j<6;j++){
                    matris[i][j]=hor[i][j-1];
                }
            }
            jTableHorarioAula.setModel(new javax.swing.table.DefaultTableModel(
                //Aquí pondremos la matriz
                matris,
                new String [] {
                    "Horario", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, true, true, true, true, true
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        }else if(nivel=='S'){
            String matris[][]=new String[8][6];
            matris[0][0]="8:00-8:45";
            matris[1][0]="8:45-9:30";
            matris[2][0]="9:30-10:15";
            matris[3][0]="10:15-11:00";
            matris[4][0]="11:00-11:30";
            matris[5][0]="11:30-12:15";
            matris[6][0]="12:15-13:00";
            matris[7][0]="13:00-13:45";
            String hor[][]=Colegio.listaAula[pos].getHa().getHor();
            for(int i=0;i<8;i++){
                for(int j=1;j<6;j++){
                    matris[i][j]=hor[i][j-1];
                }
            }
            jTableHorarioAula.setModel(new javax.swing.table.DefaultTableModel(
                //Aquí pondremos la matriz
                matris,
                new String [] {
                    "Horario", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, true, true, true, true, true
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarHorarioAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarHorarioAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarHorarioAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarHorarioAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostrarHorarioAula dialog = new MostrarHorarioAula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHorarioAula;
    // End of variables declaration//GEN-END:variables
}
