/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Clases.Colegio;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author fiore
 */
public class PanelAgenda extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgenda
     */
    public PanelAgenda() {
        initComponents();
        jTextFecha.setEditable(false);
        
        if(Colegio.idProfeIniciado ==null){
            jButtonActualizar.setVisible(true);
            jTableEventos.setEnabled(true);
        }else{
            jButtonActualizar.setVisible(false);
            jTableEventos.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEventos = new javax.swing.JTable();
        jButtonActualizar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonVerEvento = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Calendario = new rojeru_san.componentes.RSCalendar();

        setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableEventos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableEventos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8:00 - 9:00", null},
                {"9:00 - 10:00", null},
                {"10:00 - 11:00", null},
                {"11:00 - 12:00", null},
                {"13:00 - 14:00", null},
                {"14:00 - 15:00", null},
                {"15:00 - 16:00", null},
                {"16:00 - 17:00", null},
                {"17:00 - 18:00", null}
            },
            new String [] {
                "Hora", "Evento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEventos.setRowHeight(25);
        jScrollPane1.setViewportView(jTableEventos);

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Eventos");
        jLabel14.setOpaque(true);

        jTextFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha seleccionada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jButtonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(234, 234, 234))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jButtonVerEvento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVerEvento.setText("Ver Eventos");
        jButtonVerEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerEventoActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Calendario");
        jLabel13.setOpaque(true);

        Calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(Calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jButtonVerEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(344, 344, 344))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(Calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(97, 97, 97)
                .addComponent(jButtonVerEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerEventoActionPerformed
        if(Calendario.getDatoFecha()==null){
            JOptionPane.showMessageDialog(null, "Seleccione una Fecha");
        }else{
            Date fecha=Calendario.getDatoFecha();
            String formatoFecha = "dd/MM/yyyy";
            SimpleDateFormat formateador = new SimpleDateFormat(formatoFecha);

            StringTokenizer tokens=new StringTokenizer(formateador.format(fecha),"/");
            int nDatos=tokens.countTokens();
            String[] datos=new String[nDatos];
            int k=0;
            while(tokens.hasMoreTokens()){
                datos[k]=tokens.nextToken();
                k++;
            }
            int anio =Integer.parseInt(datos[2]);
            Date today = new Date();
            int anioA = today.getYear() + 1900;
            if(anio == anioA){
                int dia =Integer.parseInt(datos[0]);
                int mes =Integer.parseInt(datos[1]);
                mostrarTablaEvento(dia, mes);
                jTextFecha.setText(formateador.format(fecha));
            }else{
                JOptionPane.showMessageDialog(null, "Agenda Programada para año actual");
            }

        }
    }//GEN-LAST:event_jButtonVerEventoActionPerformed

    private void mostrarTablaEvento(int dia, int mes){
        String ev[] = Colegio.agenda.getEventos(mes, dia);
        
        for(int i = 0; i<9; i++){
            this.jTableEventos.setValueAt(ev[i], i, 1);
        }
    }

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        if(jTextFecha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccione una Fecha");
        }else{
            StringTokenizer tokens=new StringTokenizer(jTextFecha.getText(),"/");
            int nDatos=tokens.countTokens();
            String[] datos=new String[nDatos];
            int k=0;
            while(tokens.hasMoreTokens()){
                datos[k]=tokens.nextToken();
                k++;
            }
            int anio =Integer.parseInt(datos[2]);
                int dia =Integer.parseInt(datos[0]);
                int mes =Integer.parseInt(datos[1]);
                String even[] = new String[9];

                for(int i=0; i<9;i++){
                    even[i] = (String)this.jTableEventos.getValueAt(i, 1);
                }
                Colegio.agenda.setEventos(mes, dia, even);
                limpiarEventos();
                JOptionPane.showMessageDialog(null, "Eventos del día "+ jTextFecha.getText() + " actualizados correctamente");
            }
    }//GEN-LAST:event_jButtonActualizarActionPerformed
    
    private void limpiarEventos(){
         for(int i = 0; i<9; i++){
            this.jTableEventos.setValueAt("", i, 1);
        }
        jTextFecha.setText("");
     } 
    
    private void CalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalendarioMouseClicked
  
    }//GEN-LAST:event_CalendarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSCalendar Calendario;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonVerEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEventos;
    private javax.swing.JTextField jTextFecha;
    // End of variables declaration//GEN-END:variables
}
