/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Clases.*;
import Form.*;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author ARNOLD
 */
public class PanelHorarioProfe extends javax.swing.JPanel {

    /**
     * Creates new form PanelHorarioProfe
     */
    public PanelHorarioProfe() {
        initComponents();
        mostrarHorario();
    }
    
    private void mostrarHorario(){
        int pos=Colegio.existeBuscarProf(Colegio.idProfeIniciado);
        System.out.println(Colegio.listaProf[pos]);
        String hor[][]=Colegio.listaProf[pos].getHpS();
        System.out.println(hor[0][0]);
        for(int i=0;i<8;i++){
            for(int j=0;j<5;j++){
                jTableHorarioProfe.setValueAt(hor[i][j],i,j+1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHorarioProfe = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jTableHorarioProfe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableHorarioProfe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8:00-8:45", null, null, null, null, null},
                {"8:45-9:30", null, null, null, null, null},
                {"9:30-10:15", null, null, null, null, null},
                {"10:15-11:00", null, null, null, null, null},
                {"11:00-11:30", null, null, null, null, null},
                {"11:30-12:15", null, null, null, null, null},
                {"12:15-13:00", null, null, null, null, null},
                {"13:00-13:45", null, null, null, null, null}
            },
            new String [] {
                "Horario", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHorarioProfe.setRowHeight(55);
        jTableHorarioProfe.getTableHeader().setResizingAllowed(false);
        jTableHorarioProfe.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableHorarioProfe);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Imprimir Horario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Horario del Profesor");
        jLabel15.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(658, 658, 658))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Frame MainMenuAdm = null;
        new MostrarHorarioProfesor(MainMenuAdm,true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHorarioProfe;
    // End of variables declaration//GEN-END:variables
}
