/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Clases.*;
import Conexion.*;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import rsbutton.RSButtonMetro;


/**
 *
 * @author fiore
 */
public class PanelAlumnoAdm extends javax.swing.JPanel {
    
    private BD_Alumno bdAlumno = new BD_Alumno();
    private BD_Conexion BaseDatos = new BD_Conexion();
    private String sql;//Consulta a ejecutarse en la base de datos 
    private ResultSet ResultSet;//Transferir los datos de la tabla hacia un objeto
    private int cant;
    /**
     * Creates new form PanelBienvenida
     */
    public PanelAlumnoAdm() {
        
        initComponents();
        mostrarTabla();
        limpiar();
        //jTextIdAlumno.setEditable(false);
        jTextFieldCantidadAlu.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenero = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldBuscarAlu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCantidadAlu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextDireccionAlu = new javax.swing.JTextField();
        jTextIdAlumno = new javax.swing.JTextField();
        jTextApellidoAlu = new javax.swing.JTextField();
        jTextNombreAlu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonActualizarAlu = new javax.swing.JButton();
        jButtonAgregarAlu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextDniAlu = new javax.swing.JTextField();
        jRadioButtonFemenino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jSpinnerDiaNac = new javax.swing.JSpinner();
        jSpinnerMesNac = new javax.swing.JSpinner();
        jSpinnerAnioNac = new javax.swing.JSpinner();
        jButtonEliminarAlu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAlumnos);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel10.setText("Cantidad");

        jTextFieldCantidadAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadAluActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Lista de Alumnos Matriculados");
        jLabel13.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButtonBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscarAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jTextFieldBuscarAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCantidadAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(639, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(245, 244, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setName(""); // NOI18N

        jLabel1.setText("id ALumno");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Genero");

        jLabel5.setText("Direccion");

        jLabel6.setText("Dia ");

        jLabel7.setText("Mes ");

        jLabel8.setText("Año ");

        jTextIdAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdAlumnoActionPerformed(evt);
            }
        });

        jTextApellidoAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApellidoAluActionPerformed(evt);
            }
        });

        jLabel9.setText("Nacimiento");

        jButtonActualizarAlu.setText("Actualizar");
        jButtonActualizarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarAluActionPerformed(evt);
            }
        });

        jButtonAgregarAlu.setText("Agregar");
        jButtonAgregarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAluActionPerformed(evt);
            }
        });

        jLabel11.setText("DNI");

        buttonGroupGenero.add(jRadioButtonFemenino);
        jRadioButtonFemenino.setText("Femenino");
        jRadioButtonFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemeninoActionPerformed(evt);
            }
        });

        buttonGroupGenero.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("Masculino");

        jSpinnerDiaNac.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinnerMesNac.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinnerAnioNac.setModel(new javax.swing.SpinnerNumberModel(2004, 2004, 2018, 1));

        jButtonEliminarAlu.setText("Eliminar");
        jButtonEliminarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAluActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Datos de Alumno");
        jLabel12.setOpaque(true);

        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reload-3x.png"))); // NOI18N
        jButtonLimpiar.setBorder(null);
        jButtonLimpiar.setContentAreaFilled(false);
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonAgregarAlu)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonActualizarAlu)
                                .addGap(38, 38, 38)
                                .addComponent(jButtonEliminarAlu))
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerDiaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerMesNac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerAnioNac, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(jTextDireccionAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addComponent(jRadioButtonFemenino)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButtonMasculino))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel2))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNombreAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextDniAlu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextApellidoAlu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonLimpiar)
                        .addGap(34, 34, 34))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextApellidoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombreAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDniAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFemenino)
                    .addComponent(jRadioButtonMasculino)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccionAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerDiaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMesNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAnioNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarAlu)
                    .addComponent(jButtonActualizarAlu)
                    .addComponent(jButtonEliminarAlu))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void limpiar(){        
        
        jTextFieldCantidadAlu.setText(cant+"");
        jTextIdAlumno.setText("");
        jTextApellidoAlu.setText("");
        jTextNombreAlu.setText("");
        jTextDireccionAlu.setText("");
        jTextDniAlu.setText("");    
    }
    
public void mostrarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        Alumno listaAlu[] = bdAlumno.obtenerAlumnos();
        modelo.addColumn("Id");
        modelo.addColumn("Aula");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Nombre");
        modelo.addColumn("DNI");
        modelo.addColumn("Genero");
        //modelo.addColumn("Celular");
        jTableAlumnos.setModel(modelo);
         String datos[] = new String[6];
         
         System.out.println();
         cant=0;
         while(listaAlu[cant]!=null){
            String cad = listaAlu[cant].getCodigo();
            datos[0]= cad;
            System.out.println(cad);
            cad = listaAlu[cant].getCodA();
            datos[1]= cad;
            cad = listaAlu[cant].getApellido();
            datos[2]= cad;
            cad = listaAlu[cant].getNombre();
            datos[3]= cad;
            cad = listaAlu[cant].getDni();
            datos[4]= cad;
            cad = listaAlu[cant].getGenero();
            datos[5]= cad;
            //datos[5]=Colegio.listaProf[i].getCelular();
            modelo.addRow(datos);
            cant++;
        }    
        jTableAlumnos.setModel(modelo);
        
    }
     
    private void jTextApellidoAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApellidoAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApellidoAluActionPerformed

    private void jButtonActualizarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarAluActionPerformed
        int dia,mes,anio;
        Alumno a=new Alumno();
        String id = jTextIdAlumno.getText();
        if (!jTextNombreAlu.getText().isEmpty() && !jTextApellidoAlu.getText().isEmpty()
                && !jTextDniAlu.getText().isEmpty() && !jTextDireccionAlu.getText().isEmpty() && 
                (jRadioButtonFemenino.isSelected()||jRadioButtonMasculino.isSelected())){
            //int pos = Colegio.existeBuscarAlu(id);
                a.setCodigo(id);
                a.setNombre(jTextNombreAlu.getText());

                a.setApellido(jTextApellidoAlu.getText());
                try{
                    int dni=Integer.parseInt(jTextDniAlu.getText());
                    a.setDni(jTextDniAlu.getText());
                    //Validar numero de DNI Cantidad de dígitos 
                    a.setDomicilio(jTextDireccionAlu.getText());
                    dia = Integer.parseInt(jSpinnerDiaNac.getValue().toString());
                    a.setDiaNac(dia);

                    mes = Integer.parseInt(jSpinnerMesNac.getValue().toString());
                    a.setMesNac(mes);

                    anio = Integer.parseInt(jSpinnerAnioNac.getValue().toString());
                    a.setAnioNac(anio);

                    if(jRadioButtonFemenino.isSelected()){
                        a.setGenero(""+"F");
                    }else{
                        if(jRadioButtonMasculino.isSelected()){
                            a.setGenero(""+"M");
                        }
                    }
                    bdAlumno.actualizarAlumno(a);
                    JOptionPane.showMessageDialog(null, "Alumno editado correctamente");
                    mostrarTabla();
                    limpiar();
                }catch(NumberFormatException ev){
                    JOptionPane.showMessageDialog(null, "Ingrese un DNI válido");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Faltan Datos");
            }
    }//GEN-LAST:event_jButtonActualizarAluActionPerformed

    private void jButtonAgregarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAluActionPerformed
        // Boton que agrega alumnos
        Alumno a = new Alumno();
        int dia,mes,anio, idN;
        String id = jTextIdAlumno.getText();;
        if (!jTextNombreAlu.getText().isEmpty() && !jTextApellidoAlu.getText().isEmpty()
            && !jTextDniAlu.getText().isEmpty() && !jTextDireccionAlu.getText().isEmpty()){
            
            //int pos = Colegio.existeBuscarAlu(id);
            int pos=bdAlumno.existeCodigo(id);
            if(pos<0){
                a.setCodigo(id);
                a.setNombre(jTextNombreAlu.getText());

                a.setApellido(jTextApellidoAlu.getText());
                try{
                    int dni=Integer.parseInt(jTextDniAlu.getText());
                    a.setDni(jTextDniAlu.getText());
                    //Validar numero de DNI Cantidad de dígitos 
                    a.setDomicilio(jTextDireccionAlu.getText());
                    dia = Integer.parseInt(jSpinnerDiaNac.getValue().toString());
                    a.setDiaNac(dia);


                    mes = Integer.parseInt(jSpinnerMesNac.getValue().toString());
                    a.setMesNac(mes);

                    anio = Integer.parseInt(jSpinnerAnioNac.getValue().toString());
                    a.setAnioNac(anio);

                    if(jRadioButtonFemenino.isSelected()){
                        a.setGenero(""+"F");
                    }else{
                        if(jRadioButtonMasculino.isSelected()){
                            a.setGenero(""+"M");
                        }
                    }
                    bdAlumno.ingresarAlumno(a);
                    JOptionPane.showMessageDialog(null, "Alumno matriculado correctamente");
                    mostrarTabla();
                    limpiar();
                }catch(NumberFormatException ev){
                    JOptionPane.showMessageDialog(null, "Ingrese un DNI válido");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Alumno con código " + id+ " , ya existe");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }
    }//GEN-LAST:event_jButtonAgregarAluActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        limpiar();
        if (!jTextFieldBuscarAlu.getText().isEmpty()){
            String genero;
            String idB = jTextFieldBuscarAlu.getText();
            int pos = Colegio.existeBuscarAlu(idB);
            System.out.println(pos);
            Alumno listaAlu[] = bdAlumno.obtenerAlumnos();
            if(pos>=0){
                this.jTextIdAlumno.setText(listaAlu[pos].getCodigo());
                this.jTextApellidoAlu.setText(listaAlu[pos].getApellido());
                this.jTextNombreAlu.setText(listaAlu[pos].getNombre());
                this.jTextDniAlu.setText(listaAlu[pos].getDni());
                genero = listaAlu[pos].getGenero();
                if(genero.equals("F")){
                    jRadioButtonFemenino.setSelected(true);
                }else{
                    jRadioButtonMasculino.setSelected(true);
                }
                this.jTextDireccionAlu.setText(listaAlu[pos].getDomicilio());
                
                this.jSpinnerDiaNac.setValue(listaAlu[pos].getDiaNac());
                this.jSpinnerMesNac.setValue(listaAlu[pos].getMesNac());
                this.jSpinnerAnioNac.setValue(listaAlu[pos].getAnioNac());
                //this.jTextCelularPro.setText(listaProf[pos].getCelular());
            }else{
                JOptionPane.showMessageDialog(null, "Alumno con id " + idB + " NO encontrado" );
            }
        }else{
            JOptionPane.showMessageDialog(null, "Espacio Vacio");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    
    private void jRadioButtonFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemeninoActionPerformed

    private void jTextFieldCantidadAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadAluActionPerformed

    private void jTableAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlumnosMouseClicked
        int pos = this.jTableAlumnos.getSelectedRow();
        Alumno listaAlu[] = bdAlumno.obtenerAlumnos();
        //int fila = Colegio.existeBuscarAlu(this.jTableAlumnos.getValueAt(pos, 0).toString()); 
        
        this.jTextIdAlumno.setText(listaAlu[pos].getCodigo());
        this.jTextApellidoAlu.setText(listaAlu[pos].getApellido());
        this.jTextNombreAlu.setText(listaAlu[pos].getNombre());
        this.jTextDniAlu.setText(listaAlu[pos].getDni());
        //genero = Colegio.listaAlu[pos].getGenero();
        if(listaAlu[pos].getGenero().equals("F")){
            jRadioButtonFemenino.setSelected(true);
        }else
            jRadioButtonMasculino.setSelected(true);
        
        this.jTextDireccionAlu.setText(listaAlu[pos].getDomicilio());
        
        this.jSpinnerDiaNac.setValue(listaAlu[pos].getDiaNac());
        this.jSpinnerMesNac.setValue(listaAlu[pos].getMesNac());
        this.jSpinnerAnioNac.setValue(listaAlu[pos].getAnioNac());
    }//GEN-LAST:event_jTableAlumnosMouseClicked

    private void jButtonEliminarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAluActionPerformed
        if (!jTextIdAlumno.getText().isEmpty()){
           String cod = jTextIdAlumno.getText();
           int v = bdAlumno.existeCodigo(cod);

           if(v<0){
               JOptionPane.showMessageDialog(null, "Alumno No existe");
           }else{
               //Colegio.eliminarAlumno(cod);
               bdAlumno.eliminarAlumno(cod);
               JOptionPane.showMessageDialog(null, "Alumno Eliminado");
               mostrarTabla();
               limpiar();
           }     
        }else{
             JOptionPane.showMessageDialog(null, "Alumno no seleccionado");
        }   
        
        
    }//GEN-LAST:event_jButtonEliminarAluActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextIdAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.JButton jButtonActualizarAlu;
    private javax.swing.JButton jButtonAgregarAlu;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminarAlu;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFemenino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAnioNac;
    private javax.swing.JSpinner jSpinnerDiaNac;
    private javax.swing.JSpinner jSpinnerMesNac;
    private javax.swing.JTable jTableAlumnos;
    private javax.swing.JTextField jTextApellidoAlu;
    private javax.swing.JTextField jTextDireccionAlu;
    private javax.swing.JTextField jTextDniAlu;
    private javax.swing.JTextField jTextFieldBuscarAlu;
    private javax.swing.JTextField jTextFieldCantidadAlu;
    private javax.swing.JTextField jTextIdAlumno;
    private javax.swing.JTextField jTextNombreAlu;
    // End of variables declaration//GEN-END:variables

}
